name: manga_view_flutter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.4.1
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  html: ^0.15.4
  logger: ^2.5.0
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  infinite_scroll_pagination: ^4.1.0
  photo_view: ^0.14.0
  flutter_inappwebview: ^6.1.5
  package_info_plus: ^8.3.0
  flutter_adaptive_scaffold: ^0.1.7
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  webview_flutter_android: ^4.4.1
  webview_flutter_wkwebview: ^3.20.0
  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5
  mockito: ^5.4.4
  analyzer: ^5.13.0
  dart_style: ^2.3.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

